---
- name: Install MySQL 5.7 repo
  yum: 
    name: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
    state: present

- name: Install MySQL 5.7
  yum:
    name:
    - mysql-community-server
    - mysql-community-client
    - MySQL-python
    state: present

- name: Start MySQL service
  service: 
    name: mysqld 
    state: started 
    enabled: yes

- name: Remove Test database if it exist
  mysql_db: 
    name: test
    state: absent
  ignore_errors: yes

- name: Remove All Anonymous User Accounts
  mysql_user: 
    name: ''
    host_all: yes 
    state: absent
  ignore_errors: yes

- name: Change root password
  mysql_user: 
    name: root 
    host: "{{ item }}"
    password: '{{ root_db_password }}'
  loop:
      - 127.0.0.1
      - ::1
      - '{{ ansible_hostname }}'
      - localhost
  ignore_errors: yes