---
- name: Install PHP Remi Repository
  yum: 
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm 
    update_cache: yes 
    state: present

- name: Enable PHP 7.2
  shell:
    cmd: yum-config-manager --enable remi-php72

- name: Install PHP
  yum: 
    name: 
    - php
    - php-mysql
    - php-fpm
    - php-gd
    state: present