---
- name: Create MySQL schema
  mysql_db:
    name: '{{ wordpress_db_name }}'
    login_host: '{{ wordpress_db_endpoint }}'
    login_user: '{{ wordpress_db_root_user }}'
    login_password: '{{wordpress_db_root_password}}'
    state: present

- name: Create MySQL user
  mysql_user:
    name: '{{ wordpress_db_user }}'
    password: '{{ wordpress_db_pass }}'
    priv: '{{ wordpress_db_name }}.*:ALL'
    login_host: '{{ wordpress_db_endpoint }}'
    login_user: '{{ wordpress_db_root_user }}'
    login_password: '{{wordpress_db_root_password}}'
    state: present