---
- name: Download Wordpress Latest
  get_url:
    url: http://wordpress.org/{{wordpress_version}}.tar.gz
    dest: /tmp/wordpress.tar.gz
  when: wordpress_version == 'latest'

- name: Download Wordpress specific version
  get_url:
    url: http://wordpress.org/wordpress-{{wordpress_version}}.tar.gz
    dest: /tmp/wordpress.tar.gz
  when: wordpress_version != 'latest'

- name: Unzip Wordpress to /tmp
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move files to Apache root directory
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: yes
    mode: preserve

- name: Create uploads directory
  file:
    path: /var/www/html/wp-content/uploads
    state: directory
    mode: '0755'

- name: Configure Wordpress
  template: 
    src: wp-config.php.j2  
    dest: /var/www/html/wp-config.php

- name: Change Owner of directory of Apache
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: apache
    group: apache

- name: Restart Apache
  service: 
    name: httpd 
    state: restarted 

- name: Show Wordpress informations
  debug:
    msg: "Wordpres url =>  http://{{ ansible_default_ipv4.address }}/"
