---
- name: Download Wordpress Latest
  get_url:
    url: https://wordpress.org/{{wordpress_version}}.tar.gz
    dest: /tmp/wordpress.tar.gz
  # when: wordpress_version == 'latest'

# - name: Download Wordpress specific version
#   get_url:
#     url: https://wordpress.org/wordpress-{{wordpress_version}}.tar.gz
#     dest: /tmp/wordpress.tar.gz
#   when: wordpress_version != 'latest'

- name: Unzip Wordpress to /tmp
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move files to Apache root directory
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: yes
    mode: preserve

- name: Create uploads directory
  file:
    path: /var/www/html/wp-content/uploads
    state: directory
    mode: '0755'

- name: Configure Wordpress
  template: 
    src: wp-config.php.j2  
    dest: /var/www/html/wp-config.php

- name: Change Owner of directory of Apache
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: apache
    group: apache
  notify: restart apache

- name: Add .htaccess
  template: 
    src: htaccess.j2  
    dest: /var/www/html/.htaccess

- name: Show Wordpress informations
  debug:
    msg: 
    - "Wordpress informations..."
    - "Wordpres url =>  http://{{ ansible_eth1.ipv4.address }}/"
    - ""
    - "MySQL connection string => mysql -h {{wordpress_db_endpoint}} -u {{wordpress_db_user}} -p{{wordpress_db_pass}} {{wordpress_db_name}}"
