---
- include: "{{ ansible_facts['os_family'] }}/osdependencies.yml"
- include: "{{ ansible_facts['os_family'] }}/selinux.yml"
- include: "{{ ansible_facts['os_family'] }}/ntp.yml"
- include: "{{ ansible_facts['os_family'] }}/ostools.yml"